#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Workaround for: https://github.com/sorin-ionescu/prezto/issues/1744
#
export HISTFILE="${ZDOTDIR:-$HOME}/.zhistory" # The path to the history file.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# history
HISTSIZE=100000
SAVEHIST=100000

# Homebrew
export HOMEBREW_GITHUB_API_TOKEN=$(op item get "GitHub" --fields label="homebrew token" --format json | jq -r '.value')
eval $(/opt/homebrew/bin/brew shellenv)

# Powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs status)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_MODE='nerdfont-complete'

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# rbenv
#eval "$(rbenv init -)"

# kitchen-ec2
export KITCHEN_YAML=kitchen.ec2.yml

# Chef
export CHEF_GENERATOR_PATH="/Users/bkonick/workspace/cargurus/cargurus-devops/chef_v2/cg_chef_skeletons/cookbooks/cg_code_generator"

# GitHub Enterprise
export GITHUB_TOKEN=$(op item get "GitHub" --fields label=token --format json | jq -r '.value')

# Load SSH keys
ssh-add -q ~/.ssh/id_rsa
ssh-add -q ~/.ssh/cg_syseng_general
ssh-add -q ~/.ssh/cg-coresys-shared

export CHEF_LICENSE="accept"

#export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl@1.1"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# vault
export VAULT_ADDR="https://vault.na.c-gurus.com:8200"

# aliases
alias fixdns='sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache'

# nvm
#export PATH="$HOME/.nvm/versions/node/v16.13.0/bin:$PATH"
#export NVM_DIR="$HOME/.nvm"
#[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh" --no-use

# tfenv
export TFENV_AUTO_INSTALL=true
export TFENV_CONFIG_DIR="$HOME/.tfenv"

# openssl
# export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"

# go
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

# docker
export PATH=$PATH:$HOME/.docker/bin
